SUBT:=copyt

TOPDIR:=../../..
DESTDIR:=$(HOME)/.emacs.d/snippets/makefile-mode
SRCFILES:=$(wildcard *)
SRCFILES:=$(filter-out Makefile,$(SRCFILES))
SRCFILES:=$(filter-out Makefile~,$(SRCFILES))

include $(TOPDIR)/build.mak
